swagger: "2.0"
info:
  version: "0.1.0"
  title: Music service
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

  /ratefilm:
    # binds a127 app logic to a route
    x-swagger-router-controller: ratefilm-controller
    get:
      description: Returns list of ratefilm decription
      # used as the method name of the controller
      operationId: ratefilm
      parameters:
        - name: date
          in: query
          description: FIltering date
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RateFilmResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /recommendations:
    # binds a127 app logic to a route
    x-swagger-router-controller: recommendations-controller
    get:
      description: Returns list of recommendations films
      # used as the method name of the controller
      operationId: recommendations
      parameters:
        - name: date
          in: query
          description: FIltering date
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RecommendationsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  RateFilmResponse:
      type: array
      items:
        $ref: "#/definitions/Film"
        
  Film:
    required:
      - name
      - image
      - date
    properties:
      name:
        type: string
      image:
        type: string
      date:
        type: string
        
  
  RecommendationsResponse:
      type: array
      items:
        $ref: "#/definitions/Film"
        
    
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string


