swagger: "2.0"
info:
  version: "0.1.0"
  title: Music service
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /map:
    # binds a127 app logic to a route
    x-swagger-router-controller: map-controller
    get:
      description: Returns list of musical city musicevents
      # used as the method name of the controller
      operationId: map
      parameters:
        - name: date
          in: query
          description: FIltering date
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MapResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  MapResponse:
    type: array
    items:
      $ref: "#/definitions/Map"

  Map:
    required:
      - date
    properties:
      name:
        type: string
      title:
        type: string
      price:
        type: string
      sits:
        type: string
      date:
        type: string

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
